name: flutter_ecommerce_mini
description: Flutter E-Commerce Mini App 
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bloc: ^9.0.0
  connectivity_plus: ^7.0.0
  dartz: ^0.10.1
  dio: ^5.9.0
  equatable: ^2.0.7
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get: ^4.7.2
  get_it: ^8.2.0
  go_router: ^16.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.5.0
  intl: ^0.20.2
  js: ^0.7.2
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.5.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/facebook.png
    - assets/google.png
    - assets/apple.png
    - assets/avatar.png